name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: composer:v2
          coverage: none
      
      - name: Setup Minio Client and Download Storage
        run: |
          wget -q https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc alias set remote/ https://cdn.shyim.de ${{ secrets.ACCESS_KEY }} ${{ secrets.ACCESS_SECRET }}
          mkdir indexes
          ./mc cp -r remote/phpstorm/ $(pwd)/indexes/
          
      - name: Clone Shopware and run Composer install
        run: |
          git clone https://github.com/shopware/development.git --depth=1 development
          cd development
          rm -rf platform
          git clone https://github.com/shopware/platform.git --depth=1
          composer install

      - name: Download PhpStorm
        run: |
          wget -q https://download-cf.jetbrains.com/webide/PhpStorm-2021.1.tar.gz
          tar xfv PhpStorm-2021.1.tar.gz
          rm PhpStorm-2021.1.tar.gz
          mv PhpStorm* PhpStorm
          mkdir generated-cache
          
      - name: Generate Cache
        run: ./PhpStorm/bin/phpstorm.sh dump-shared-index project --output=$(pwd)/generated-cache --tmp=/tmp/phpstorm --project-dir=$(pwd)/development/ --project-id=sw6_tpl_development_trunk
        
      - name: Generate Cache Map
        run: |
          mv $(pwd)/generated-cache/* $(pwd)/indexes
          wget -q https://packages.jetbrains.team/maven/p/ij/intellij-shared-indexes-public/com/jetbrains/intellij/indexing/shared/cdn-layout-tool/0.7.52/cdn-layout-tool-0.7.52.zip
          unzip cdn-layout-tool-0.7.52.zip
          export JAVA_HOME=$(pwd)/PhpStorm/jbr/
          ./cdn-layout-tool-0.7.52/bin/cdn-layout-tool --indexes-dir=$(pwd)/indexes --url=https://cdn.shyim.de/phpstorm
          
      - name: Upload to Minio
        run: |
          ./mc cp -r $(pwd)/indexes/* remote/phpstorm

      
