name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none
      
      - name: Setup Minio Client and Download Storage
        run: |
          wget -q https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          ./mc alias set remote/ https://963ff7fb9c523564b5f3a398ab39d488.r2.cloudflarestorage.com ${{ secrets.ACCESS_KEY }} ${{ secrets.ACCESS_SECRET }}
          mkdir indexes
          # ./mc cp -r remote/phpstorm/ $(pwd)/indexes/
          
      - name: Clone Shopware and run Composer install
        run: |
          git clone https://github.com/shopware/platform.git --depth=1
          cd platform
          composer install
          cp -R ../.idea .
          ls -la

      - name: Download PhpStorm
        run: |
          wget -q https://download-cdn.jetbrains.com/webide/PhpStorm-2022.3.1.tar.gz
          tar xfv PhpStorm-2022.3.1.tar.gz
          rm PhpStorm-2022.3.1.tar.gz
          mv PhpStorm* PhpStorm
          mkdir generated-cache
          cp -R plugins/* ./PhpStorm/plugins/
          ls -la ./PhpStorm/plugins/
          
      - name: Generate Cache
        run: ./PhpStorm/bin/phpstorm.sh dump-shared-index project --output=$(pwd)/generated-cache --tmp=/tmp/phpstorm --project-dir=$(pwd)/platform/ --project-id=sw6_trunk
        
      - name: Generate Cache Map
        run: |
          mv $(pwd)/generated-cache/* $(pwd)/indexes
          wget -q https://packages.jetbrains.team/maven/p/ij/intellij-shared-indexes-public/com/jetbrains/intellij/indexing/shared/cdn-layout-tool/0.8.66/cdn-layout-tool-0.8.66.zip
          unzip cdn-layout-tool-0.8.66.zip
          export JAVA_HOME=$(pwd)/PhpStorm/jbr/
          ./cdn-layout-tool-0.8.66/bin/cdn-layout-tool --indexes-dir=$(pwd)/indexes --url=https://pub-8c005513525c430f8ed741a5e080379f.r2.dev
          
      - name: Upload to Minio
        run: |
          ./mc cp -r $(pwd)/indexes/* remote/shopware-jetbrains

      
