name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Jetbrains
        uses: actions/cache@v3
        with:
          path: ~/.cache/JetBrains/
          key: ${{ runner.os }}-trunk-2022.3.1
      
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18

      - name: Clone Shopware and run Composer install
        run: |
          git clone https://github.com/shopware/platform.git --depth=1
          cd platform
          composer install
          npm install --prefix src/Administration/Resources/app/administration install
          npm install --prefix src/Storefront/Resources/app/storefront install
          cp -R ../.idea .

      - name: Download PhpStorm
        run: |
          wget -q https://download-cdn.jetbrains.com/webide/PhpStorm-2022.3.1.tar.gz
          tar xf PhpStorm-2022.3.1.tar.gz
          rm PhpStorm-2022.3.1.tar.gz
          mv PhpStorm* PhpStorm
          mkdir generated-cache
          cp -R plugins/* ./PhpStorm/plugins/
          ls -la ./PhpStorm/plugins/
          
      - name: Generate Cache
        run: ./PhpStorm/bin/phpstorm.sh dump-shared-index project --output=$(pwd)/generated-cache --tmp=/tmp/phpstorm --project-dir=$(pwd)/platform/ --project-id=sw6_trunk
        
      - name: Generate Cache Map
        run: |
          mv $(pwd)/generated-cache/* $(pwd)/indexes
          wget -q https://packages.jetbrains.team/maven/p/ij/intellij-shared-indexes-public/com/jetbrains/intellij/indexing/shared/cdn-layout-tool/0.8.66/cdn-layout-tool-0.8.66.zip
          unzip cdn-layout-tool-0.8.66.zip
          export JAVA_HOME=$(pwd)/PhpStorm/jbr/
          ./cdn-layout-tool-0.8.66/bin/cdn-layout-tool --indexes-dir=$(pwd)/indexes --url=https://doex1q8n3l36c.cloudfront.net
          
      - name: AWS Deploy
        run: aws s3 sync $(pwd)/indexes/* s3://shopware-jetbrains
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACCESS_SECRET }}
          AWS_DEFAULT_REGION: eu-central-1

      
